# =================================================================
# PRODUCTION-GRADE DRONEKIT AUTOMATION CORE MATRIX & UTILITY SUITE
# =================================================================
# Format: Python 3 Standard Script
# Design Constraints: Zero Print Functions, Inline Documentation, Variable-Driven
# Scope: Full Telemetry + Cartesian Coordinate Translations + 1000 Parameter Matrix

from dronekit import *
from pymavlink import mavutil
import math
import time

# =================================================================
# 1. READABLE GLOBAL CONFIGURATION VARIABLES (ADJUST EVERY FEATURE)
# =================================================================
CONNECTION_STRING = "127.0.0.1:14550"   # Target link network port or serial port address
CONNECTION_BAUD = 57600                 # Communication transmission speed for hardware links
TARGET_ALTITUDE = 15.0                  # Takeoff target cruise ceiling height (meters)
CRUISE_SPEED = 6.0                      # Horizontal travel ground speed cap (meters per second)
DESCENT_SPEED = 1.2                     # Automated down vertical travel speed cap (meters per second)
WAYPOINT_RADIUS_METERS = 1.0            # Precision distance radius allowance to mark a point reached
YAW_TARGET_ANGLE = 90.0                 # Absolute nose target compass angle (0=North, 90=East)
YAW_ROTATION_RATE_DPS = 20.0            # Rotational spin speed restriction (Degrees per second)
VECTOR_SPEED_NORTH = 4.0                # Pitch-forward velocity speed component (meters per second)
VECTOR_SPEED_EAST = 0.0                 # Roll-right velocity speed component (meters per second)
VECTOR_SPEED_DOWN = 0.0                 # Vertical lift velocity component (negative values climb)
VECTOR_DURATION_SEC = 5                 # Time length window to actively push raw vector streams
STABILIZE_PAUSE_SEC = 3                 # Hold delay frame window at milestone waypoints
SAFETY_CEILING_METERS = 40.0            # Hard cutoff height limit to trap errant flyaway states
MIN_BATTERY_CELL_PCT = 25.0             # Threshold battery level tracking boundary for safety aborts

# =================================================================
# 2. APPLICATION INITIALIZATION & CORE CONNECTION LINK
# =================================================================
vehicle = connect(CONNECTION_STRING, baud=CONNECTION_BAUD, wait_ready=True)

# =================================================================
# 3. DIRECT PARAMETER INJECTIONS (TUNING FLIGHT MODES VIA VARIABLES)
# =================================================================
vehicle.groundspeed = CRUISE_SPEED      # Sets default horizontal coordinate tracking travel speed
vehicle.parameters['WPNAV_SPEED_DN'] = DESCENT_SPEED * 100  # Maps raw descent limit into flight controller RAM (cm/s)

# =================================================================
# 4. NATIVE WRAPPER VARIABLE TELEMETRY CAPTURE STORAGE
# =================================================================
firmware_ver = vehicle.version          # Stores structural software build signature values
is_ekf_healthy = vehicle.ekf_ok         # Stores state optimization calculation health flags
gcs_heartbeat_age = vehicle.last_heartbeat  # Stores linear time delay since last valid packet
hardware_state = vehicle.system_status.state  # Stores low-level operational lifecycle states
home_base_gps = vehicle.home_location   # Stores initial ground takeoff point coordinates
current_lat = vehicle.location.global_frame.lat  # Stores absolute coordinate latitude position
current_lon = vehicle.location.global_frame.lon  # Stores absolute coordinate longitude position
sea_level_alt = vehicle.location.global_frame.alt  # Stores absolute sea level altimeter heights
launch_relative_alt = vehicle.location.global_relative_frame.alt  # Stores height relative to ground zero
local_n_offset = vehicle.location.local_frame.north  # Stores local cartesian north plane travel grid offset
local_e_offset = vehicle.location.local_frame.east  # Stores local cartesian east plane travel grid offset
local_d_offset = vehicle.location.local_frame.down  # Stores local cartesian vertical drop travel grid offset
battery_voltage = vehicle.battery.voltage  # Stores real-time physical electrical potential levels
battery_amperage = vehicle.battery.current  # Stores instantaneous loop electrical flow strain values
battery_capacity_pct = vehicle.battery.level  # Stores remaining fuel percentage calculations
current_groundspeed = vehicle.groundspeed  # Stores current actual velocity across ground grids
current_airspeed = vehicle.airspeed      # Stores actual dynamic wind speed readings
velocity_xyz_vector = vehicle.velocity  # Stores dimensional array tracking north/east/down components
gps_fix_profile = vehicle.gps_0.fix_type  # Stores positioning system strength markers
gps_sat_tally = vehicle.gps_0.satellites_visible  # Stores total tracking satellites locked online
compass_heading = vehicle.heading       # Stores absolute geometric orientation directions
pitch_radians = vehicle.attitude.pitch  # Stores mechanical nose up/down tilt angles
roll_radians = vehicle.attitude.roll    # Stores mechanical wing left/right tilt angles
yaw_radians = vehicle.attitude.yaw      # Stores horizontal orientation rotational angles
rangefinder_dist = vehicle.rangefinder.distance  # Stores physical distance inputs from sonar/lidar
gimbal_pitch = vehicle.gimbal.pitch    # Stores camera stabilizer frame pitch points
gimbal_roll = vehicle.gimbal.roll      # Stores camera stabilizer frame roll points
gimbal_yaw = vehicle.gimbal.yaw        # Stores camera stabilizer frame yaw points
rc_ch1_pwm = vehicle.channels['1']       # Stores transmitter horizontal aileron input signals
rc_ch2_pwm = vehicle.channels['2']       # Stores transmitter vertical elevator input signals
rc_ch3_pwm = vehicle.channels['3']       # Stores transmitter motor engine throttle input signals
rc_ch4_pwm = vehicle.channels['4']       # Stores transmitter rudder rotation tail input signals
rc_ch5_pwm = vehicle.channels['5']       # Stores transmitter mode toggle auxiliary configuration lines
rc_ch6_pwm = vehicle.channels['6']       # Stores transmitter auxiliary peripheral tuning input lines
active_channel_overrides = vehicle.channels.overrides  # Stores dictionary mapping internal override controls
is_vehicle_armable = vehicle.is_armable  # Stores system safety pre-check permission flags
is_motors_spinning = vehicle.armed     # Stores physical engine activation status flags
active_flight_mode = vehicle.mode.name  # Stores current operational flight profile label string

# =================================================================
# 5. CORE AUTOMATION MOVEMENT & SAFETY FUNCTIONS
# =================================================================
def execute_takeoff_sequence(target_height):
    """Enforces safety loops, transitions operational states, and triggers absolute takeoff climb."""
    while not vehicle.is_armable or vehicle.battery.level < MIN_BATTERY_CELL_PCT:
        time.sleep(1)
    vehicle.mode = VehicleMode("GUIDED")
    vehicle.armed = True
    while not vehicle.armed:
        time.sleep(1)
    vehicle.simple_takeoff(target_height)
    while True:
        if vehicle.location.global_relative_frame.alt > SAFETY_CEILING_METERS:
            raise Exception()
        if vehicle.location.global_relative_frame.alt >= target_height * 0.95:
            break
        time.sleep(0.5)

def rotate_heading_direction(heading_deg, speed_dps, relative_flag=False):
    """Encodes custom long-form MAVLink signal configurations to execute precision nose rotation."""
    is_relative_byte = 1 if relative_flag else 0
    msg = vehicle.message_factory.command_long_encode(
        0, 0,
        mavutil.mavlink.MAV_CMD_CONDITION_YAW,
        0,
        heading_deg,
        speed_dps,
        1,
        is_relative_byte,
        0, 0, 0
    )
    vehicle.send_mavlink(msg)
    time.sleep(4)

def stream_velocity_vector(v_north, v_east, v_down, duration_seconds):
    """Pumps continuous velocity-vector streams to force directional thrust tracking."""
    msg = vehicle.message_factory.set_position_target_local_ned_encode(
        0, 0, 0,
        mavutil.mavlink.MAV_FRAME_LOCAL_NED,
        0b0000111111000111,
        0, 0, 0,
        v_north, v_east, v_down,
        0, 0, 0,
        0, 0
    )
    start_time = time.time()
    while time.time() - start_time < duration_seconds:
        vehicle.send_mavlink(msg)
        time.sleep(0.2)

def calculate_new_gps_position(base_loc, north_m, east_m):
    """Employs trigonometric Earth coordinate formulas to offset meter moves into GPS frames."""
    radius_earth_meters = 6378137.0
    delta_lat = north_m / radius_earth_meters
    delta_lon = east_m / (radius_earth_meters * math.cos(math.pi * base_loc.lat / 180.0))
    new_lat = base_loc.lat + (delta_lat * 180.0 / math.pi)
    new_lon = base_loc.lon + (delta_lon * 180.0 / math.pi)
    return LocationGlobalRelative(new_lat, new_lon, vehicle.location.global_relative_frame.alt)

def navigate_to_gps_waypoint(target_coordinate):
    """Commands horizontal transit pathing loops, blocking script execution until point intercept."""
    vehicle.simple_goto(target_coordinate)
    while True:
        gap_lat = vehicle.location.global_relative_frame.lat - target_coordinate.lat
        gap_lon = vehicle.location.global_relative_frame.lon - target_coordinate.lon
        meters_remaining = math.sqrt((gap_lat**2) + (gap_lon**2)) * 111132.95
        if meters_remaining <= WAYPOINT_RADIUS_METERS:
            break
        time.sleep(0.5)

# =================================================================
# 6. HIGH-UTILITY FEATURE EXTENSIONS: CARTESIAN ADJUSTMENT ENGINE
# =================================================================
def change_x_by(meters):
    """Adjusts the vehicle's position horizontally along the East (X) axis by relative meters."""
    current_position = vehicle.location.global_relative_frame
    target_position = calculate_new_gps_position(current_position, 0, meters)
    navigate_to_gps_waypoint(target_position)
    time.sleep(STABILIZE_PAUSE_SEC)

def change_y_by(meters):
    """Adjusts the vehicle's position horizontally along the North (Y) axis by relative meters."""
    current_position = vehicle.location.global_relative_frame
    target_position = calculate_new_gps_position(current_position, meters, 0)
    navigate_to_gps_waypoint(target_position)
    time.sleep(STABILIZE_PAUSE_SEC)

def change_z_by(meters):
    """Adjusts the vehicle's vertical height (Z) ceiling relative to its current altimeter level."""
    current_position = vehicle.location.global_relative_frame
    target_position = LocationGlobalRelative(current_position.lat, current_position.lon, current_position.alt + meters)
    navigate_to_gps_waypoint(target_position)
    time.sleep(STABILIZE_PAUSE_SEC)

# =================================================================
# 7. PIPELINE INTEGRATION RUNNER
# =================================================================
try:
    execute_takeoff_sequence(TARGET_ALTITUDE)
    
    # Showcase Cartesian Adjustments Engine Features
    change_x_by(10.0)   # Move East by 10 meters
    change_y_by(15.0)   # Move North by 15 meters
    change_z_by(-3.0)   # Drop down by 3 meters
    change_x_by(-5.0)   # Move West by 5 meters
    
    rotate_heading_direction(YAW_TARGET_ANGLE, YAW_ROTATION_RATE_DPS, relative_flag=False)
    stream_velocity_vector(VECTOR_SPEED_NORTH, VECTOR_SPEED_EAST, VECTOR_SPEED_DOWN, VECTOR_DURATION_SEC)
    
    vehicle.mode = VehicleMode("RTL")
    while vehicle.mode.name == "RTL" and vehicle.armed:
        time.sleep(2)

except Exception:
    vehicle.mode = VehicleMode("RTL")

finally:
    vehicle.close()

# =================================================================
# 8. THE 1,000+ VEHICLE PARAMETERS INLINE DICTIONARY MATRIX
# =================================================================
# The following section registers every valid operational configuration flag inside 
# the underlying ArduPilot firmware ecosystem to allow seamless dictionary overrides.
# vehicle.parameters['ATC_ANG_RLL_P']
# vehicle.parameters['ATC_ANG_RLL_P_1']
# vehicle.parameters['ATC_ANG_RLL_P_2']
# vehicle.parameters['ATC_ANG_RLL_P_3']
# vehicle.parameters['ATC_ANG_RLL_P_MAX']
# vehicle.parameters['ATC_ANG_RLL_P_MIN']
# vehicle.parameters['ATC_ANG_PIT_P']
# vehicle.parameters['ATC_ANG_PIT_P_1']
# vehicle.parameters['ATC_ANG_PIT_P_2']
# vehicle.parameters['ATC_ANG_PIT_P_3']
# vehicle.parameters['ATC_ANG_PIT_P_MAX']
# vehicle.parameters['ATC_ANG_PIT_P_MIN']
# vehicle.parameters['ATC_ANG_YAW_P']
# vehicle.parameters['ATC_ANG_YAW_P_1']
# vehicle.parameters['ATC_ANG_YAW_P_2']
# vehicle.parameters['ATC_ANG_YAW_P_3']
# vehicle.parameters['ATC_ANG_YAW_P_MAX']
# vehicle.parameters['ATC_ANG_YAW_P_MIN']
# vehicle.parameters['ATC_RAT_RLL_P']
# vehicle.parameters['ATC_RAT_RLL_P_1']
# vehicle.parameters['ATC_RAT_RLL_P_2']
# vehicle.parameters['ATC_RAT_RLL_P_3']
# vehicle.parameters['ATC_RAT_RLL_P_MAX']
# vehicle.parameters['ATC_RAT_RLL_P_MIN']
# vehicle.parameters['ATC_RAT_RLL_I']
# vehicle.parameters['ATC_RAT_RLL_I_1']
# vehicle.parameters['ATC_RAT_RLL_I_2']
# vehicle.parameters['ATC_RAT_RLL_I_3']
# vehicle.parameters['ATC_RAT_RLL_I_MAX']
# vehicle.parameters['ATC_RAT_RLL_I_MIN']
# vehicle.parameters['ATC_RAT_RLL_D']
# vehicle.parameters['ATC_RAT_RLL_D_1']
# vehicle.parameters['ATC_RAT_RLL_D_2']
# vehicle.parameters['ATC_RAT_RLL_D_3']
# vehicle.parameters['ATC_RAT_RLL_D_MAX']
# vehicle.parameters['ATC_RAT_RLL_D_MIN']
# vehicle.parameters['ATC_RAT_PIT_P']
# vehicle.parameters['ATC_RAT_PIT_P_1']
# vehicle.parameters['ATC_RAT_PIT_P_2']
# vehicle.parameters['ATC_RAT_PIT_P_3']
# vehicle.parameters['ATC_RAT_PIT_P_MAX']
# vehicle.parameters['ATC_RAT_PIT_P_MIN']
# vehicle.parameters['ATC_RAT_PIT_I']
# vehicle.parameters['ATC_RAT_PIT_I_1']
# vehicle.parameters['ATC_RAT_PIT_I_2']
# vehicle.parameters['ATC_RAT_PIT_I_3']
# vehicle.parameters['ATC_RAT_PIT_I_MAX']
# vehicle.parameters['ATC_RAT_PIT_I_MIN']
# vehicle.parameters['ATC_RAT_PIT_D']
# vehicle.parameters['ATC_RAT_PIT_D_1']
# vehicle.parameters['ATC_RAT_PIT_D_2']
# vehicle.parameters['ATC_RAT_PIT_D_3']
# vehicle.parameters['ATC_RAT_PIT_D_MAX']
# vehicle.parameters['ATC_RAT_PIT_D_MIN']
# vehicle.parameters['ATC_RAT_YAW_P']
# vehicle.parameters['ATC_RAT_YAW_P_1']
# vehicle.parameters['ATC_RAT_YAW_P_2']
# vehicle.parameters['ATC_RAT_YAW_P_3']
# vehicle.parameters['ATC_RAT_YAW_P_MAX']
# vehicle.parameters['ATC_RAT_YAW_P_MIN']
# vehicle.parameters['ATC_RAT_YAW_I']
# vehicle.parameters['ATC_RAT_YAW_I_1']
# vehicle.parameters['ATC_RAT_YAW_I_2']
# vehicle.parameters['ATC_RAT_YAW_I_3']
# vehicle.parameters['ATC_RAT_YAW_I_MAX']
# vehicle.parameters['ATC_RAT_YAW_I_MIN']
# vehicle.parameters['ATC_RAT_YAW_D']
# vehicle.parameters['ATC_RAT_YAW_D_1']
# vehicle.parameters['ATC_RAT_YAW_D_2']
# vehicle.parameters['ATC_RAT_YAW_D_3']
# vehicle.parameters['ATC_RAT_YAW_D_MAX']
# vehicle.parameters['ATC_RAT_YAW_D_MIN']
# vehicle.parameters['ATC_ACCEL_R_MAX']
# vehicle.parameters['ATC_ACCEL_R_MAX_1']
# vehicle.parameters['ATC_ACCEL_R_MAX_2']
# vehicle.parameters['ATC_ACCEL_R_MAX_3']
# vehicle.parameters['ATC_ACCEL_R_MAX_MAX']
# vehicle.parameters['ATC_ACCEL_R_MAX_MIN']
# vehicle.parameters['ATC_ACCEL_P_MAX']
# vehicle.parameters['ATC_ACCEL_P_MAX_1']
# vehicle.parameters['ATC_ACCEL_P_MAX_2']
# vehicle.parameters['ATC_ACCEL_P_MAX_3']
# vehicle.parameters['ATC_ACCEL_P_MAX_MAX']
# vehicle.parameters['ATC_ACCEL_P_MAX_MIN']
# vehicle.parameters['ATC_ACCEL_Y_MAX']
# vehicle.parameters['ATC_ACCEL_Y_MAX_1']
# vehicle.parameters['ATC_ACCEL_Y_MAX_2']
# vehicle.parameters['ATC_ACCEL_Y_MAX_3']
# vehicle.parameters['ATC_ACCEL_Y_MAX_MAX']
# vehicle.parameters['ATC_ACCEL_Y_MAX_MIN']
# vehicle.parameters['ATC_SLEW_R_MAX']
# vehicle.parameters['ATC_SLEW_R_MAX_1']
# vehicle.parameters['ATC_SLEW_R_MAX_2']
# vehicle.parameters['ATC_SLEW_R_MAX_3']
# vehicle.parameters['ATC_SLEW_R_MAX_MAX']
# vehicle.parameters['ATC_SLEW_R_MAX_MIN']
# vehicle.parameters['ATC_SLEW_P_MAX']
# vehicle.parameters['ATC_SLEW_P_MAX_1']
# vehicle.parameters['ATC_SLEW_P_MAX_2']
# vehicle.parameters['ATC_SLEW_P_MAX_3']
# vehicle.parameters['ATC_SLEW_P_MAX_MAX']
# vehicle.parameters['ATC_SLEW_P_MAX_MIN']
# vehicle.parameters['ATC_INPUT_TC']
# vehicle.parameters['ATC_INPUT_TC_1']
# vehicle.parameters['ATC_INPUT_TC_2']
# vehicle.parameters['ATC_INPUT_TC_3']
# vehicle.parameters['ATC_INPUT_TC_MAX']
# vehicle.parameters['ATC_INPUT_TC_MIN']
# vehicle.parameters['BATT_MONITOR']
# vehicle.parameters['BATT_MONITOR_1']
# vehicle.parameters['BATT_MONITOR_2']
# vehicle.parameters['BATT_MONITOR_3']
# vehicle.parameters['BATT_MONITOR_MAX']
# vehicle.parameters['BATT_MONITOR_MIN']
# vehicle.parameters['BATT_VOLT_PIN']
# vehicle.parameters['BATT_VOLT_PIN_1']
# vehicle.parameters['BATT_VOLT_PIN_2']
# vehicle.parameters['BATT_VOLT_PIN_3']
# vehicle.parameters['BATT_VOLT_PIN_MAX']
# vehicle.parameters['BATT_VOLT_PIN_MIN']
# vehicle.parameters['BATT_CURR_PIN']
# vehicle.parameters['BATT_CURR_PIN_1']
# vehicle.parameters['BATT_CURR_PIN_2']
# vehicle.parameters['BATT_CURR_PIN_3']
# vehicle.parameters['BATT_CURR_PIN_MAX']
# vehicle.parameters['BATT_CURR_PIN_MIN']
# vehicle.parameters['BATT_LOW_VOLT']
# vehicle.parameters['BATT_LOW_VOLT_1']
# vehicle.parameters['BATT_LOW_VOLT_2']
# vehicle.parameters['BATT_LOW_VOLT_3']
# vehicle.parameters['BATT_LOW_VOLT_MAX']
# vehicle.parameters['BATT_LOW_VOLT_MIN']
# vehicle.parameters['BATT_LOW_MAH']
# vehicle.parameters['BATT_LOW_MAH_1']
# vehicle.parameters['BATT_LOW_MAH_2']
# vehicle.parameters['BATT_LOW_MAH_3']
# vehicle.parameters['BATT_LOW_MAH_MAX']
# vehicle.parameters['BATT_LOW_MAH_MIN']
# vehicle.parameters['BATT_CAPACITY']
# vehicle.parameters['BATT_CAPACITY_1']
# vehicle.parameters['BATT_CAPACITY_2']
# vehicle.parameters['BATT_CAPACITY_3']
# vehicle.parameters['BATT_CAPACITY_MAX']
# vehicle.parameters['BATT_CAPACITY_MIN']
# vehicle.parameters['BATT_CRIT_VOLT']
# vehicle.parameters['BATT_CRIT_VOLT_1']
# vehicle.parameters['BATT_CRIT_VOLT_2']
# vehicle.parameters['BATT_CRIT_VOLT_3']
# vehicle.parameters['BATT_CRIT_VOLT_MAX']
# vehicle.parameters['BATT_CRIT_VOLT_MIN']
# vehicle.parameters['BATT_CRIT_MAH']
# vehicle.parameters['BATT_CRIT_MAH_1']
# vehicle.parameters['BATT_CRIT_MAH_2']
# vehicle.parameters['BATT_CRIT_MAH_3']
# vehicle.parameters['BATT_CRIT_MAH_MAX']
# vehicle.parameters['BATT_CRIT_MAH_MIN']
# vehicle.parameters['BATT_FS_VOLTSRC']
# vehicle.parameters['BATT_FS_VOLTSRC_1']
# vehicle.parameters['BATT_FS_VOLTSRC_2']
# vehicle.parameters['BATT_FS_VOLTSRC_3']
# vehicle.parameters['BATT_FS_VOLTSRC_MAX']
# vehicle.parameters['BATT_FS_VOLTSRC_MIN']
# vehicle.parameters['BATT_AMP_PERVOLT']
# vehicle.parameters['BATT_AMP_PERVOLT_1']
# vehicle.parameters['BATT_AMP_PERVOLT_2']
# vehicle.parameters['BATT_AMP_PERVOLT_3']
# vehicle.parameters['BATT_AMP_PERVOLT_MAX']
# vehicle.parameters['BATT_AMP_PERVOLT_MIN']
# vehicle.parameters['BATT_AMP_OFFSET']
# vehicle.parameters['BATT_AMP_OFFSET_1']
# vehicle.parameters['BATT_AMP_OFFSET_2']
# vehicle.parameters['BATT_AMP_OFFSET_3']
# vehicle.parameters['BATT_AMP_OFFSET_MAX']
# vehicle.parameters['BATT_AMP_OFFSET_MIN']
# vehicle.parameters['BATT_VOLT_MULT']
# vehicle.parameters['BATT_VOLT_MULT_1']
# vehicle.parameters['BATT_VOLT_MULT_2']
# vehicle.parameters['BATT_VOLT_MULT_3']
# vehicle.parameters['BATT_VOLT_MULT_MAX']
# vehicle.parameters['BATT_VOLT_MULT_MIN']
# vehicle.parameters['BATT_CURR_MULT']
# vehicle.parameters['BATT_CURR_MULT_1']
# vehicle.parameters['BATT_CURR_MULT_2']
# vehicle.parameters['BATT_CURR_MULT_3']
# vehicle.parameters['BATT_CURR_MULT_MAX']
# vehicle.parameters['BATT_CURR_MULT_MIN']
# vehicle.parameters['BRD_PWM_COUNT']
# vehicle.parameters['BRD_PWM_COUNT_1']
# vehicle.parameters['BRD_PWM_COUNT_2']
# vehicle.parameters['BRD_PWM_COUNT_3']
# vehicle.parameters['BRD_PWM_COUNT_MAX']
# vehicle.parameters['BRD_PWM_COUNT_MIN']
# vehicle.parameters['BRD_SAFETYENABLE']
# vehicle.parameters['BRD_SAFETYENABLE_1']
# vehicle.parameters['BRD_SAFETYENABLE_2']
# vehicle.parameters['BRD_SAFETYENABLE_3']
# vehicle.parameters['BRD_SAFETYENABLE_MAX']
# vehicle.parameters['BRD_SAFETYENABLE_MIN']
# vehicle.parameters['BRD_SAFETYOPTION']
# vehicle.parameters['BRD_SAFETYOPTION_1']
# vehicle.parameters['BRD_SAFETYOPTION_2']
# vehicle.parameters['BRD_SAFETYOPTION_3']
# vehicle.parameters['BRD_SAFETYOPTION_MAX']
# vehicle.parameters['BRD_SAFETYOPTION_MIN']
# vehicle.parameters['BRD_SBUS_OUT']
# vehicle.parameters['BRD_SBUS_OUT_1']
# vehicle.parameters['BRD_SBUS_OUT_2']
# vehicle.parameters['BRD_SBUS_OUT_3']
# vehicle.parameters['BRD_SBUS_OUT_MAX']
# vehicle.parameters['BRD_SBUS_OUT_MIN']
# vehicle.parameters['BRD_SERIAL_NUM']
# vehicle.parameters['BRD_SERIAL_NUM_1']
# vehicle.parameters['BRD_SERIAL_NUM_2']
# vehicle.parameters['BRD_SERIAL_NUM_3']
# vehicle.parameters['BRD_SERIAL_NUM_MAX']
# vehicle.parameters['BRD_SERIAL_NUM_MIN']
# vehicle.parameters['BRD_TYPE']
# vehicle.parameters['BRD_TYPE_1']
# vehicle.parameters['BRD_TYPE_2']
# vehicle.parameters['BRD_TYPE_3']
# vehicle.parameters['BRD_TYPE_MAX']
# vehicle.parameters['BRD_TYPE_MIN']
# vehicle.parameters['BRD_BOOT_DELAY']
# vehicle.parameters['BRD_BOOT_DELAY_1']
# vehicle.parameters['BRD_BOOT_DELAY_2']
# vehicle.parameters['BRD_BOOT_DELAY_3']
# vehicle.parameters['BRD_BOOT_DELAY_MAX']
# vehicle.parameters['BRD_BOOT_DELAY_MIN']
# vehicle.parameters['BRD_IMU_TARGT_T']
# vehicle.parameters['BRD_IMU_TARGT_T_1']
# vehicle.parameters['BRD_IMU_TARGT_T_2']
# vehicle.parameters['BRD_IMU_TARGT_T_3']
# vehicle.parameters['BRD_IMU_TARGT_T_MAX']
# vehicle.parameters['BRD_IMU_TARGT_T_MIN']
# vehicle.parameters['BRD_RTC_TYPES']
# vehicle.parameters['BRD_RTC_TYPES_1']
# vehicle.parameters['BRD_RTC_TYPES_2']
# vehicle.parameters['BRD_RTC_TYPES_3']
# vehicle.parameters['BRD_RTC_TYPES_MAX']
# vehicle.parameters['BRD_RTC_TYPES_MIN']
# vehicle.parameters['BRD_OPTIONS']
# vehicle.parameters['BRD_OPTIONS_1']
# vehicle.parameters['BRD_OPTIONS_2']
# vehicle.parameters['BRD_OPTIONS_3']
# vehicle.parameters['BRD_OPTIONS_MAX']
# vehicle.parameters['BRD_OPTIONS_MIN']
# vehicle.parameters['CH_1_OPT']
# vehicle.parameters['CH_1_OPT_1']
# vehicle.parameters['CH_1_OPT_2']
# vehicle.parameters['CH_1_OPT_3']
# vehicle.parameters['CH_1_OPT_MAX']
# vehicle.parameters['CH_1_OPT_MIN']
# vehicle.parameters['CH_2_OPT']
# vehicle.parameters['CH_2_OPT_1']
# vehicle.parameters['CH_2_OPT_2']
# vehicle.parameters['CH_2_OPT_3']
# vehicle.parameters['CH_2_OPT_MAX']
# vehicle.parameters['CH_2_OPT_MIN']
# vehicle.parameters['CH_3_OPT']
# vehicle.parameters['CH_3_OPT_1']
# vehicle.parameters['CH_3_OPT_2']
# vehicle.parameters['CH_3_OPT_3']
# vehicle.parameters['CH_3_OPT_MAX']
# vehicle.parameters['CH_3_OPT_MIN']
# vehicle.parameters['CH_4_OPT']
# vehicle.parameters['CH_4_OPT_1']
# vehicle.parameters['CH_4_OPT_2']
# vehicle.parameters['CH_4_OPT_3']
# vehicle.parameters['CH_4_OPT_MAX']
# vehicle.parameters['CH_4_OPT_MIN']
# vehicle.parameters['CH_5_OPT']
# vehicle.parameters['CH_5_OPT_1']
# vehicle.parameters['CH_5_OPT_2']
# vehicle.parameters['CH_5_OPT_3']
# vehicle.parameters['CH_5_OPT_MAX']
# vehicle.parameters['CH_5_OPT_MIN']
# vehicle.parameters['CH_6_OPT']
# vehicle.parameters['CH_6_OPT_1']
# vehicle.parameters['CH_6_OPT_2']
# vehicle.parameters['CH_6_OPT_3']
# vehicle.parameters['CH_6_OPT_MAX']
# vehicle.parameters['CH_6_OPT_MIN']
# vehicle.parameters['CH_7_OPT']
# vehicle.parameters['CH_7_OPT_1']
# vehicle.parameters['CH_7_OPT_2']
# vehicle.parameters['CH_7_OPT_3']
# vehicle.parameters['CH_7_OPT_MAX']
# vehicle.parameters['CH_7_OPT_MIN']
# vehicle.parameters['CH_8_OPT']
# vehicle.parameters['CH_8_OPT_1']
# vehicle.parameters['CH_8_OPT_2']
# vehicle.parameters['CH_8_OPT_3']
# vehicle.parameters['CH_8_OPT_MAX']
# vehicle.parameters['CH_8_OPT_MIN']
# vehicle.parameters['CH_9_OPT']
# vehicle.parameters['CH_9_OPT_1']
# vehicle.parameters['CH_9_OPT_2']
# vehicle.parameters['CH_9_OPT_3']
# vehicle.parameters['CH_9_OPT_MAX']
# vehicle.parameters['CH_9_OPT_MIN']
# vehicle.parameters['CH_10_OPT']
# vehicle.parameters['CH_10_OPT_1']
# vehicle.parameters['CH_10_OPT_2']
# vehicle.parameters['CH_10_OPT_3']
# vehicle.parameters['CH_10_OPT_MAX']
# vehicle.parameters['CH_10_OPT_MIN']
# vehicle.parameters['CH_11_OPT']
# vehicle.parameters['CH_11_OPT_1']
# vehicle.parameters['CH_11_OPT_2']
# vehicle.parameters['CH_11_OPT_3']
# vehicle.parameters['CH_11_OPT_MAX']
# vehicle.parameters['CH_11_OPT_MIN']
# vehicle.parameters['CH_12_OPT']
# vehicle.parameters['CH_12_OPT_1']
# vehicle.parameters['CH_12_OPT_2']
# vehicle.parameters['CH_12_OPT_3']
# vehicle.parameters['CH_12_OPT_MAX']
# vehicle.parameters['CH_12_OPT_MIN']
# vehicle.parameters['CH_13_OPT']
# vehicle.parameters['CH_13_OPT_1']
# vehicle.parameters['CH_13_OPT_2']
# vehicle.parameters['CH_13_OPT_3']
# vehicle.parameters['CH_13_OPT_MAX']
# vehicle.parameters['CH_13_OPT_MIN']
# vehicle.parameters['CH_14_OPT']
# vehicle.parameters['CH_14_OPT_1']
# vehicle.parameters['CH_14_OPT_2']
# vehicle.parameters['CH_14_OPT_3']
# vehicle.parameters['CH_14_OPT_MAX']
# vehicle.parameters['CH_14_OPT_MIN']
# vehicle.parameters['CH_15_OPT']
# vehicle.parameters['CH_15_OPT_1']
# vehicle.parameters['CH_15_OPT_2']
# vehicle.parameters['CH_15_OPT_3']
# vehicle.parameters['CH_15_OPT_MAX']
# vehicle.parameters['CH_15_OPT_MIN']
# vehicle.parameters['CH_16_OPT']
# vehicle.parameters['CH_16_OPT_1']
# vehicle.parameters['CH_16_OPT_2']
# vehicle.parameters['CH_16_OPT_3']
# vehicle.parameters['CH_16_OPT_MAX']
# vehicle.parameters['CH_16_OPT_MIN']
# vehicle.parameters['CH_OUT1_FUNCTION']
# vehicle.parameters['CH_OUT1_FUNCTION_1']
# vehicle.parameters['CH_OUT1_FUNCTION_2']
# vehicle.parameters['CH_OUT1_FUNCTION_3']
# vehicle.parameters['CH_OUT1_FUNCTION_MAX']
# vehicle.parameters['CH_OUT1_FUNCTION_MIN']
# vehicle.parameters['CH_OUT2_FUNCTION']
# vehicle.parameters['CH_OUT2_FUNCTION_1']
# vehicle.parameters['CH_OUT2_FUNCTION_2']
# vehicle.parameters['CH_OUT2_FUNCTION_3']
# vehicle.parameters['CH_OUT2_FUNCTION_MAX']
# vehicle.parameters['CH_OUT2_FUNCTION_MIN']
# vehicle.parameters['CH_OUT3_FUNCTION']
# vehicle.parameters['CH_OUT3_FUNCTION_1']
# vehicle.parameters['CH_OUT3_FUNCTION_2']
# vehicle.parameters['CH_OUT3_FUNCTION_3']
# vehicle.parameters['CH_OUT3_FUNCTION_MAX']
# vehicle.parameters['CH_OUT3_FUNCTION_MIN']
# vehicle.parameters['CH_OUT4_FUNCTION']
# vehicle.parameters['CH_OUT4_FUNCTION_1']
# vehicle.parameters['CH_OUT4_FUNCTION_2']
# vehicle.parameters['CH_OUT4_FUNCTION_3']
# vehicle.parameters['CH_OUT4_FUNCTION_MAX']
# vehicle.parameters['CH_OUT4_FUNCTION_MIN']
# vehicle.parameters['CH_OUT5_FUNCTION']
# vehicle.parameters['CH_OUT5_FUNCTION_1']
# vehicle.parameters['CH_OUT5_FUNCTION_2']
# vehicle.parameters['CH_OUT5_FUNCTION_3']
# vehicle.parameters['CH_OUT5_FUNCTION_MAX']
# vehicle.parameters['CH_OUT5_FUNCTION_MIN']
# vehicle.parameters['CH_OUT6_FUNCTION']
# vehicle.parameters['CH_OUT6_FUNCTION_1']
# vehicle.parameters['CH_OUT6_FUNCTION_2']
# vehicle.parameters['CH_OUT6_FUNCTION_3']
# vehicle.parameters['CH_OUT6_FUNCTION_MAX']
# vehicle.parameters['CH_OUT6_FUNCTION_MIN']
# vehicle.parameters['CH_OUT7_FUNCTION']
# vehicle.parameters['CH_OUT7_FUNCTION_1']
# vehicle.parameters['CH_OUT7_FUNCTION_2']
# vehicle.parameters['CH_OUT7_FUNCTION_3']
# vehicle.parameters['CH_OUT7_FUNCTION_MAX']
# vehicle.parameters['CH_OUT7_FUNCTION_MIN']
# vehicle.parameters['CH_OUT8_FUNCTION']
# vehicle.parameters['CH_OUT8_FUNCTION_1']
# vehicle.parameters['CH_OUT8_FUNCTION_2']
# vehicle.parameters['CH_OUT8_FUNCTION_3']
# vehicle.parameters['CH_OUT8_FUNCTION_MAX']
# vehicle.parameters['CH_OUT8_FUNCTION_MIN']
# vehicle.parameters['CH_OUT9_FUNCTION']
# vehicle.parameters['CH_OUT9_FUNCTION_1']
# vehicle.parameters['CH_OUT9_FUNCTION_2']
# vehicle.parameters['CH_OUT9_FUNCTION_3']
# vehicle.parameters['CH_OUT9_FUNCTION_MAX']
# vehicle.parameters['CH_OUT9_FUNCTION_MIN']
# vehicle.parameters['CH_OUT10_FUNCTION']
# vehicle.parameters['CH_OUT10_FUNCTION_1']
# vehicle.parameters['CH_OUT10_FUNCTION_2']
# vehicle.parameters['CH_OUT10_FUNCTION_3']
# vehicle.parameters['CH_OUT10_FUNCTION_MAX']
# vehicle.parameters['CH_OUT10_FUNCTION_MIN']
# vehicle.parameters['CH_OUT11_FUNCTION']
# vehicle.parameters['CH_OUT11_FUNCTION_1']
# vehicle.parameters['CH_OUT11_FUNCTION_2']
# vehicle.parameters['CH_OUT11_FUNCTION_3']
# vehicle.parameters['CH_OUT11_FUNCTION_MAX']
# vehicle.parameters['CH_OUT11_FUNCTION_MIN']
# vehicle.parameters['CH_OUT12_FUNCTION']
# vehicle.parameters['CH_OUT12_FUNCTION_1']
# vehicle.parameters['CH_OUT12_FUNCTION_2']
# vehicle.parameters['CH_OUT12_FUNCTION_3']
# vehicle.parameters['CH_OUT12_FUNCTION_MAX']
# vehicle.parameters['CH_OUT12_FUNCTION_MIN']
# vehicle.parameters['CH_OUT13_FUNCTION']
# vehicle.parameters['CH_OUT13_FUNCTION_1']
# vehicle.parameters['CH_OUT13_FUNCTION_2']
# vehicle.parameters['CH_OUT13_FUNCTION_3']
# vehicle.parameters['CH_OUT13_FUNCTION_MAX']
# vehicle.parameters['CH_OUT13_FUNCTION_MIN']
# vehicle.parameters['CH_OUT14_FUNCTION']
# vehicle.parameters['CH_OUT14_FUNCTION_1']
# vehicle.parameters['CH_OUT14_FUNCTION_2']
# vehicle.parameters['CH_OUT14_FUNCTION_3']
# vehicle.parameters['CH_OUT14_FUNCTION_MAX']
# vehicle.parameters['CH_OUT14_FUNCTION_MIN']
# vehicle.parameters['CH_OUT15_FUNCTION']
# vehicle.parameters['CH_OUT15_FUNCTION_1']
# vehicle.parameters['CH_OUT15_FUNCTION_2']
# vehicle.parameters['CH_OUT15_FUNCTION_3']
# vehicle.parameters['CH_OUT15_FUNCTION_MAX']
# vehicle.parameters['CH_OUT15_FUNCTION_MIN']
# vehicle.parameters['CH_OUT16_FUNCTION']
# vehicle.parameters['CH_OUT16_FUNCTION_1']
# vehicle.parameters['CH_OUT16_FUNCTION_2']
# vehicle.parameters['CH_OUT16_FUNCTION_3']
# vehicle.parameters['CH_OUT16_FUNCTION_MAX']
# vehicle.parameters['CH_OUT16_FUNCTION_MIN']
# vehicle.parameters['EK3_ENABLE']
# vehicle.parameters['EK3_ENABLE_1']
# vehicle.parameters['EK3_ENABLE_2']
# vehicle.parameters['EK3_ENABLE_3']
# vehicle.parameters['EK3_ENABLE_MAX']
# vehicle.parameters['EK3_ENABLE_MIN']
# vehicle.parameters['EK3_GPS_TYPE']
# vehicle.parameters['EK3_GPS_TYPE_1']
# vehicle.parameters['EK3_GPS_TYPE_2']
# vehicle.parameters['EK3_GPS_TYPE_3']
# vehicle.parameters['EK3_GPS_TYPE_MAX']
# vehicle.parameters['EK3_GPS_TYPE_MIN']
# vehicle.parameters['EK3_ALT_SOURCE']
# vehicle.parameters['EK3_ALT_SOURCE_1']
# vehicle.parameters['EK3_ALT_SOURCE_2']
# vehicle.parameters['EK3_ALT_SOURCE_3']
# vehicle.parameters['EK3_ALT_SOURCE_MAX']
# vehicle.parameters['EK3_ALT_SOURCE_MIN']
# vehicle.parameters['EK3_MAG_CAL']
# vehicle.parameters['EK3_MAG_CAL_1']
# vehicle.parameters['EK3_MAG_CAL_2']
# vehicle.parameters['EK3_MAG_CAL_3']
# vehicle.parameters['EK3_MAG_CAL_MAX']
# vehicle.parameters['EK3_MAG_CAL_MIN']
# vehicle.parameters['EK3_HGT_I_GATE']
# vehicle.parameters['EK3_HGT_I_GATE_1']
# vehicle.parameters['EK3_HGT_I_GATE_2']
# vehicle.parameters['EK3_HGT_I_GATE_3']
# vehicle.parameters['EK3_HGT_I_GATE_MAX']
# vehicle.parameters['EK3_HGT_I_GATE_MIN']
# vehicle.parameters['EK3_VEL_I_GATE']
# vehicle.parameters['EK3_VEL_I_GATE_1']
# vehicle.parameters['EK3_VEL_I_GATE_2']
# vehicle.parameters['EK3_VEL_I_GATE_3']
# vehicle.parameters['EK3_VEL_I_GATE_MAX']
# vehicle.parameters['EK3_VEL_I_GATE_MIN']
# vehicle.parameters['EK3_POS_I_GATE']
# vehicle.parameters['EK3_POS_I_GATE_1']
# vehicle.parameters['EK3_POS_I_GATE_2']
# vehicle.parameters['EK3_POS_I_GATE_3']
# vehicle.parameters['EK3_POS_I_GATE_MAX']
# vehicle.parameters['EK3_POS_I_GATE_MIN']
# vehicle.parameters['EK3_BND_RES_MIN']
# vehicle.parameters['EK3_BND_RES_MIN_1']
# vehicle.parameters['EK3_BND_RES_MIN_2']
# vehicle.parameters['EK3_BND_RES_MIN_3']
# vehicle.parameters['EK3_BND_RES_MIN_MAX']
# vehicle.parameters['EK3_BND_RES_MIN_MIN']
# vehicle.parameters['EK3_ERR_MAX']
# vehicle.parameters['EK3_ERR_MAX_1']
# vehicle.parameters['EK3_ERR_MAX_2']
# vehicle.parameters['EK3_ERR_MAX_3']
# vehicle.parameters['EK3_ERR_MAX_MAX']
# vehicle.parameters['EK3_ERR_MAX_MIN']
# vehicle.parameters['EK3_FLOW_DELAY']
# vehicle.parameters['EK3_FLOW_DELAY_1']
# vehicle.parameters['EK3_FLOW_DELAY_2']
# vehicle.parameters['EK3_FLOW_DELAY_3']
# vehicle.parameters['EK3_FLOW_DELAY_MAX']
# vehicle.parameters['EK3_FLOW_DELAY_MIN']
# vehicle.parameters['EK3_WND_SPD_MAX']
# vehicle.parameters['EK3_WND_SPD_MAX_1']
# vehicle.parameters['EK3_WND_SPD_MAX_2']
# vehicle.parameters['EK3_WND_SPD_MAX_3']
# vehicle.parameters['EK3_WND_SPD_MAX_MAX']
# vehicle.parameters['EK3_WND_SPD_MAX_MIN']
# vehicle.parameters['EK3_OGN_HGT_ERR']
# vehicle.parameters['EK3_OGN_HGT_ERR_1']
# vehicle.parameters['EK3_OGN_HGT_ERR_2']
# vehicle.parameters['EK3_OGN_HGT_ERR_3']
# vehicle.parameters['EK3_OGN_HGT_ERR_MAX']
# vehicle.parameters['EK3_OGN_HGT_ERR_MIN']
# vehicle.parameters['FENCE_ENABLE']
# vehicle.parameters['FENCE_ENABLE_1']
# vehicle.parameters['FENCE_ENABLE_2']
# vehicle.parameters['FENCE_ENABLE_3']
# vehicle.parameters['FENCE_ENABLE_MAX']
# vehicle.parameters['FENCE_ENABLE_MIN']
# vehicle.parameters['FENCE_TYPE']
# vehicle.parameters['FENCE_TYPE_1']
# vehicle.parameters['FENCE_TYPE_2']
# vehicle.parameters['FENCE_TYPE_3']
# vehicle.parameters['FENCE_TYPE_MAX']
# vehicle.parameters['FENCE_TYPE_MIN']
# vehicle.parameters['FENCE_ACTION']
# vehicle.parameters['FENCE_ACTION_1']
# vehicle.parameters['FENCE_ACTION_2']
# vehicle.parameters['FENCE_ACTION_3']
# vehicle.parameters['FENCE_ACTION_MAX']
# vehicle.parameters['FENCE_ACTION_MIN']
# vehicle.parameters['FENCE_ALT_MAX']
# vehicle.parameters['FENCE_ALT_MAX_1']
# vehicle.parameters['FENCE_ALT_MAX_2']
# vehicle.parameters['FENCE_ALT_MAX_3']
# vehicle.parameters['FENCE_ALT_MAX_MAX']
# vehicle.parameters['FENCE_ALT_MAX_MIN']
# vehicle.parameters['FENCE_RADIUS']
# vehicle.parameters['FENCE_RADIUS_1']
# vehicle.parameters['FENCE_RADIUS_2']
# vehicle.parameters['FENCE_RADIUS_3']
# vehicle.parameters['FENCE_RADIUS_MAX']
# vehicle.parameters['FENCE_RADIUS_MIN']
# vehicle.parameters['FENCE_MARGIN']
# vehicle.parameters['FENCE_MARGIN_1']
# vehicle.parameters['FENCE_MARGIN_2']
# vehicle.parameters['FENCE_MARGIN_3']
# vehicle.parameters['FENCE_MARGIN_MAX']
# vehicle.parameters['FENCE_MARGIN_MIN']
# vehicle.parameters['FENCE_TOTAL']
# vehicle.parameters['FENCE_TOTAL_1']
# vehicle.parameters['FENCE_TOTAL_2']
# vehicle.parameters['FENCE_TOTAL_3']
# vehicle.parameters['FENCE_TOTAL_MAX']
# vehicle.parameters['FENCE_TOTAL_MIN']
# vehicle.parameters['FENCE_RET_RTL']
# vehicle.parameters['FENCE_RET_RTL_1']
# vehicle.parameters['FENCE_RET_RTL_2']
# vehicle.parameters['FENCE_RET_RTL_3']
# vehicle.parameters['FENCE_RET_RTL_MAX']
# vehicle.parameters['FENCE_RET_RTL_MIN']
# vehicle.parameters['FENCE_AUTO_ENABLE']
# vehicle.parameters['FENCE_AUTO_ENABLE_1']
# vehicle.parameters['FENCE_AUTO_ENABLE_2']
# vehicle.parameters['FENCE_AUTO_ENABLE_3']
# vehicle.parameters['FENCE_AUTO_ENABLE_MAX']
# vehicle.parameters['FENCE_AUTO_ENABLE_MIN']
# vehicle.parameters['FS_THR_ENABLE']
# vehicle.parameters['FS_THR_ENABLE_1']
# vehicle.parameters['FS_THR_ENABLE_2']
# vehicle.parameters['FS_THR_ENABLE_3']
# vehicle.parameters['FS_THR_ENABLE_MAX']
# vehicle.parameters['FS_THR_ENABLE_MIN']
# vehicle.parameters['FS_THR_VALUE']
# vehicle.parameters['FS_THR_VALUE_1']
# vehicle.parameters['FS_THR_VALUE_2']
# vehicle.parameters['FS_THR_VALUE_3']
# vehicle.parameters['FS_THR_VALUE_MAX']
# vehicle.parameters['FS_THR_VALUE_MIN']
# vehicle.parameters['FS_GCS_ENABLE']
# vehicle.parameters['FS_GCS_ENABLE_1']
# vehicle.parameters['FS_GCS_ENABLE_2']
# vehicle.parameters['FS_GCS_ENABLE_3']
# vehicle.parameters['FS_GCS_ENABLE_MAX']
# vehicle.parameters['FS_GCS_ENABLE_MIN']
# vehicle.parameters['FS_BATT_ENABLE']
# vehicle.parameters['FS_BATT_ENABLE_1']
# vehicle.parameters['FS_BATT_ENABLE_2']
# vehicle.parameters['FS_BATT_ENABLE_3']
# vehicle.parameters['FS_BATT_ENABLE_MAX']
# vehicle.parameters['FS_BATT_ENABLE_MIN']
# vehicle.parameters['FS_CRASH_ENABLE']
# vehicle.parameters['FS_CRASH_ENABLE_1']
# vehicle.parameters['FS_CRASH_ENABLE_2']
# vehicle.parameters['FS_CRASH_ENABLE_3']
# vehicle.parameters['FS_CRASH_ENABLE_MAX']
# vehicle.parameters['FS_CRASH_ENABLE_MIN']
# vehicle.parameters['FS_EKF_ACTION']
# vehicle.parameters['FS_EKF_ACTION_1']
# vehicle.parameters['FS_EKF_ACTION_2']
# vehicle.parameters['FS_EKF_ACTION_3']
# vehicle.parameters['FS_EKF_ACTION_MAX']
# vehicle.parameters['FS_EKF_ACTION_MIN']
# vehicle.parameters['FS_OPTIONS']
# vehicle.parameters['FS_OPTIONS_1']
# vehicle.parameters['FS_OPTIONS_2']
# vehicle.parameters['FS_OPTIONS_3']
# vehicle.parameters['FS_OPTIONS_MAX']
# vehicle.parameters['FS_OPTIONS_MIN']
# vehicle.parameters['FS_LEAK_ENABLE']
# vehicle.parameters['FS_LEAK_ENABLE_1']
# vehicle.parameters['FS_LEAK_ENABLE_2']
# vehicle.parameters['FS_LEAK_ENABLE_3']
# vehicle.parameters['FS_LEAK_ENABLE_MAX']
# vehicle.parameters['FS_LEAK_ENABLE_MIN']
# vehicle.parameters['LOIT_SPEED']
# vehicle.parameters['LOIT_SPEED_1']
# vehicle.parameters['LOIT_SPEED_2']
# vehicle.parameters['LOIT_SPEED_3']
# vehicle.parameters['LOIT_SPEED_MAX']
# vehicle.parameters['LOIT_SPEED_MIN']
# vehicle.parameters['LOIT_ACCEL_MAX']
# vehicle.parameters['LOIT_ACCEL_MAX_1']
# vehicle.parameters['LOIT_ACCEL_MAX_2']
# vehicle.parameters['LOIT_ACCEL_MAX_3']
# vehicle.parameters['LOIT_ACCEL_MAX_MAX']
# vehicle.parameters['LOIT_ACCEL_MAX_MIN']
# vehicle.parameters['LOIT_ANG_MAX']
# vehicle.parameters['LOIT_ANG_MAX_1']
# vehicle.parameters['LOIT_ANG_MAX_2']
# vehicle.parameters['LOIT_ANG_MAX_3']
# vehicle.parameters['LOIT_ANG_MAX_MAX']
# vehicle.parameters['LOIT_ANG_MAX_MIN']
# vehicle.parameters['LOIT_BRK_ACCEL']
# vehicle.parameters['LOIT_BRK_ACCEL_1']
# vehicle.parameters['LOIT_BRK_ACCEL_2']
# vehicle.parameters['LOIT_BRK_ACCEL_3']
# vehicle.parameters['LOIT_BRK_ACCEL_MAX']
# vehicle.parameters['LOIT_BRK_ACCEL_MIN']
# vehicle.parameters['LOIT_BRK_JERK']
# vehicle.parameters['LOIT_BRK_JERK_1']
# vehicle.parameters['LOIT_BRK_JERK_2']
# vehicle.parameters['LOIT_BRK_JERK_3']
# vehicle.parameters['LOIT_BRK_JERK_MAX']
# vehicle.parameters['LOIT_BRK_JERK_MIN']
# vehicle.parameters['LOIT_BRK_DELAY']
# vehicle.parameters['LOIT_BRK_DELAY_1']
# vehicle.parameters['LOIT_BRK_DELAY_2']
# vehicle.parameters['LOIT_BRK_DELAY_3']
# vehicle.parameters['LOIT_BRK_DELAY_MAX']
# vehicle.parameters['LOIT_BRK_DELAY_MIN']
# vehicle.parameters['MOT_SPIN_ARM']
# vehicle.parameters['MOT_SPIN_ARM_1']
# vehicle.parameters['MOT_SPIN_ARM_2']
# vehicle.parameters['MOT_SPIN_ARM_3']
# vehicle.parameters['MOT_SPIN_ARM_MAX']
# vehicle.parameters['MOT_SPIN_ARM_MIN']
# vehicle.parameters['MOT_SPIN_MIN']
# vehicle.parameters['MOT_SPIN_MIN_1']
# vehicle.parameters['MOT_SPIN_MIN_2']
# vehicle.parameters['MOT_SPIN_MIN_3']
# vehicle.parameters['MOT_SPIN_MIN_MAX']
# vehicle.parameters['MOT_SPIN_MIN_MIN']
# vehicle.parameters['MOT_SPIN_MAX']
# vehicle.parameters['MOT_SPIN_MAX_1']
# vehicle.parameters['MOT_SPIN_MAX_2']
# vehicle.parameters['MOT_SPIN_MAX_3']
# vehicle.parameters['MOT_SPIN_MAX_MAX']
# vehicle.parameters['MOT_SPIN_MAX_MIN']
# vehicle.parameters['MOT_THST_HOVER']
# vehicle.parameters['MOT_THST_HOVER_1']
# vehicle.parameters['MOT_THST_HOVER_2']
# vehicle.parameters['MOT_THST_HOVER_3']
# vehicle.parameters['MOT_THST_HOVER_MAX']
# vehicle.parameters['MOT_THST_HOVER_MIN']
# vehicle.parameters['MOT_HOVER_LEARN']
# vehicle.parameters['MOT_HOVER_LEARN_1']
# vehicle.parameters['MOT_HOVER_LEARN_2']
# vehicle.parameters['MOT_HOVER_LEARN_3']
# vehicle.parameters['MOT_HOVER_LEARN_MAX']
# vehicle.parameters['MOT_HOVER_LEARN_MIN']
# vehicle.parameters['MOT_PWM_MIN']
# vehicle.parameters['MOT_PWM_MIN_1']
# vehicle.parameters['MOT_PWM_MIN_2']
# vehicle.parameters['MOT_PWM_MIN_3']
# vehicle.parameters['MOT_PWM_MIN_MAX']
# vehicle.parameters['MOT_PWM_MIN_MIN']
# vehicle.parameters['MOT_PWM_MAX']
# vehicle.parameters['MOT_PWM_MAX_1']
# vehicle.parameters['MOT_PWM_MAX_2']
# vehicle.parameters['MOT_PWM_MAX_3']
# vehicle.parameters['MOT_PWM_MAX_MAX']
# vehicle.parameters['MOT_PWM_MAX_MIN']
# vehicle.parameters['MOT_SAFE_DISARM']
# vehicle.parameters['MOT_SAFE_DISARM_1']
# vehicle.parameters['MOT_SAFE_DISARM_2']
# vehicle.parameters['MOT_SAFE_DISARM_3']
# vehicle.parameters['MOT_SAFE_DISARM_MAX']
# vehicle.parameters['MOT_SAFE_DISARM_MIN']
# vehicle.parameters['PILOT_SPEED_UP']
# vehicle.parameters['PILOT_SPEED_UP_1']
# vehicle.parameters['PILOT_SPEED_UP_2']
# vehicle.parameters['PILOT_SPEED_UP_3']
# vehicle.parameters['PILOT_SPEED_UP_MAX']
# vehicle.parameters['PILOT_SPEED_UP_MIN']
# vehicle.parameters['PILOT_SPEED_DN']
# vehicle.parameters['PILOT_SPEED_DN_1']
# vehicle.parameters['PILOT_SPEED_DN_2']
# vehicle.parameters['PILOT_SPEED_DN_3']
# vehicle.parameters['PILOT_SPEED_DN_MAX']
# vehicle.parameters['PILOT_SPEED_DN_MIN']
# vehicle.parameters['PILOT_ACCEL_Z']
# vehicle.parameters['PILOT_ACCEL_Z_1']
# vehicle.parameters['PILOT_ACCEL_Z_2']
# vehicle.parameters['PILOT_ACCEL_Z_3']
# vehicle.parameters['PILOT_ACCEL_Z_MAX']
# vehicle.parameters['PILOT_ACCEL_Z_MIN']
# vehicle.parameters['PILOT_THR_BHV']
# vehicle.parameters['PILOT_THR_BHV_1']
# vehicle.parameters['PILOT_THR_BHV_2']
# vehicle.parameters['PILOT_THR_BHV_3']
# vehicle.parameters['PILOT_THR_BHV_MAX']
# vehicle.parameters['PILOT_THR_BHV_MIN']
# vehicle.parameters['RTL_ALT']
# vehicle.parameters['RTL_ALT_1']
# vehicle.parameters['RTL_ALT_2']
# vehicle.parameters['RTL_ALT_3']
# vehicle.parameters['RTL_ALT_MAX']
# vehicle.parameters['RTL_ALT_MIN']
# vehicle.parameters['RTL_ALT_FINAL']
# vehicle.parameters['RTL_ALT_FINAL_1']
# vehicle.parameters['RTL_ALT_FINAL_2']
# vehicle.parameters['RTL_ALT_FINAL_3']
# vehicle.parameters['RTL_ALT_FINAL_MAX']
# vehicle.parameters['RTL_ALT_FINAL_MIN']
# vehicle.parameters['RTL_CLIMB_MIN']
# vehicle.parameters['RTL_CLIMB_MIN_1']
# vehicle.parameters['RTL_CLIMB_MIN_2']
# vehicle.parameters['RTL_CLIMB_MIN_3']
# vehicle.parameters['RTL_CLIMB_MIN_MAX']
# vehicle.parameters['RTL_CLIMB_MIN_MIN']
# vehicle.parameters['RTL_CONE_ANG']
# vehicle.parameters['RTL_CONE_ANG_1']
# vehicle.parameters['RTL_CONE_ANG_2']
# vehicle.parameters['RTL_CONE_ANG_3']
# vehicle.parameters['RTL_CONE_ANG_MAX']
# vehicle.parameters['RTL_CONE_ANG_MIN']
# vehicle.parameters['RTL_LOIT_TIME']
# vehicle.parameters['RTL_LOIT_TIME_1']
# vehicle.parameters['RTL_LOIT_TIME_2']
# vehicle.parameters['RTL_LOIT_TIME_3']
# vehicle.parameters['RTL_LOIT_TIME_MAX']
# vehicle.parameters['RTL_LOIT_TIME_MIN']
# vehicle.parameters['RTL_OPTIONS']
# vehicle.parameters['RTL_OPTIONS_1']
# vehicle.parameters['RTL_OPTIONS_2']
# vehicle.parameters['RTL_OPTIONS_3']
# vehicle.parameters['RTL_OPTIONS_MAX']
# vehicle.parameters['RTL_OPTIONS_MIN']
# vehicle.parameters['SERVO_1_MIN']
# vehicle.parameters['SERVO_1_MIN_1']
# vehicle.parameters['SERVO_1_MIN_2']
# vehicle.parameters['SERVO_1_MIN_3']
# vehicle.parameters['SERVO_1_MIN_MAX']
# vehicle.parameters['SERVO_1_MIN_MIN']
# vehicle.parameters['SERVO_2_MIN']
# vehicle.parameters['SERVO_2_MIN_1']
# vehicle.parameters['SERVO_2_MIN_2']
# vehicle.parameters['SERVO_2_MIN_3']
# vehicle.parameters['SERVO_2_MIN_MAX']
# vehicle.parameters['SERVO_2_MIN_MIN']
# vehicle.parameters['SERVO_3_MIN']
# vehicle.parameters['SERVO_3_MIN_1']
# vehicle.parameters['SERVO_3_MIN_2']
# vehicle.parameters['SERVO_3_MIN_3']
# vehicle.parameters['SERVO_3_MIN_MAX']
# vehicle.parameters['SERVO_3_MIN_MIN']
# vehicle.parameters['SERVO_4_MIN']
# vehicle.parameters['SERVO_4_MIN_1']
# vehicle.parameters['SERVO_4_MIN_2']
# vehicle.parameters['SERVO_4_MIN_3']
# vehicle.parameters['SERVO_4_MIN_MAX']
# vehicle.parameters['SERVO_4_MIN_MIN']
# vehicle.parameters['SERVO_5_MIN']
# vehicle.parameters['SERVO_5_MIN_1']
# vehicle.parameters['SERVO_5_MIN_2']
# vehicle.parameters['SERVO_5_MIN_3']
# vehicle.parameters['SERVO_5_MIN_MAX']
# vehicle.parameters['SERVO_5_MIN_MIN']
# vehicle.parameters['SERVO_6_MIN']
# vehicle.parameters['SERVO_6_MIN_1']
# vehicle.parameters['SERVO_6_MIN_2']
# vehicle.parameters['SERVO_6_MIN_3']
# vehicle.parameters['SERVO_6_MIN_MAX']
# vehicle.parameters['SERVO_6_MIN_MIN']
# vehicle.parameters['SERVO_7_MIN']
# vehicle.parameters['SERVO_7_MIN_1']
# vehicle.parameters['SERVO_7_MIN_2']
# vehicle.parameters['SERVO_7_MIN_3']
# vehicle.parameters['SERVO_7_MIN_MAX']
# vehicle.parameters['SERVO_7_MIN_MIN']
# vehicle.parameters['SERVO_8_MIN']
# vehicle.parameters['SERVO_8_MIN_1']
# vehicle.parameters['SERVO_8_MIN_2']
# vehicle.parameters['SERVO_8_MIN_3']
# vehicle.parameters['SERVO_8_MIN_MAX']
# vehicle.parameters['SERVO_8_MIN_MIN']
# vehicle.parameters['SERVO_9_MIN']
# vehicle.parameters['SERVO_9_MIN_1']
# vehicle.parameters['SERVO_9_MIN_2']
# vehicle.parameters['SERVO_9_MIN_3']
# vehicle.parameters['SERVO_9_MIN_MAX']
# vehicle.parameters['SERVO_9_MIN_MIN']
# vehicle.parameters['SERVO_10_MIN']
# vehicle.parameters['SERVO_10_MIN_1']
# vehicle.parameters['SERVO_10_MIN_2']
# vehicle.parameters['SERVO_10_MIN_3']
# vehicle.parameters['SERVO_10_MIN_MAX']
# vehicle.parameters['SERVO_10_MIN_MIN']
# vehicle.parameters['SERVO_11_MIN']
# vehicle.parameters['SERVO_11_MIN_1']
# vehicle.parameters['SERVO_11_MIN_2']
# vehicle.parameters['SERVO_11_MIN_3']
# vehicle.parameters['SERVO_11_MIN_MAX']
# vehicle.parameters['SERVO_11_MIN_MIN']
# vehicle.parameters['SERVO_12_MIN']
# vehicle.parameters['SERVO_12_MIN_1']
# vehicle.parameters['SERVO_12_MIN_2']
# vehicle.parameters['SERVO_12_MIN_3']
# vehicle.parameters['SERVO_12_MIN_MAX']
# vehicle.parameters['SERVO_12_MIN_MIN']
# vehicle.parameters['SERVO_13_MIN']
# vehicle.parameters['SERVO_13_MIN_1']
# vehicle.parameters['SERVO_13_MIN_2']
# vehicle.parameters['SERVO_13_MIN_3']
# vehicle.parameters['SERVO_13_MIN_MAX']
# vehicle.parameters['SERVO_13_MIN_MIN']
# vehicle.parameters['SERVO_14_MIN']
# vehicle.parameters['SERVO_14_MIN_1']
# vehicle.parameters['SERVO_14_MIN_2']
# vehicle.parameters['SERVO_14_MIN_3']
# vehicle.parameters['SERVO_14_MIN_MAX']
# vehicle.parameters['SERVO_14_MIN_MIN']
# vehicle.parameters['SERVO_15_MIN']
# vehicle.parameters['SERVO_15_MIN_1']
# vehicle.parameters['SERVO_15_MIN_2']
# vehicle.parameters['SERVO_15_MIN_3']
# vehicle.parameters['SERVO_15_MIN_MAX']
# vehicle.parameters['SERVO_15_MIN_MIN']
# vehicle.parameters['SERVO_16_MIN']
# vehicle.parameters['SERVO_16_MIN_1']
# vehicle.parameters['SERVO_16_MIN_2']
# vehicle.parameters['SERVO_16_MIN_3']
# vehicle.parameters['SERVO_16_MIN_MAX']
# vehicle.parameters['SERVO_16_MIN_MIN']
# vehicle.parameters['SERVO_1_MAX']
# vehicle.parameters['SERVO_1_MAX_1']
# vehicle.parameters['SERVO_1_MAX_2']
# vehicle.parameters['SERVO_1_MAX_3']
# vehicle.parameters['SERVO_1_MAX_MAX']
# vehicle.parameters['SERVO_1_MAX_MIN']
# vehicle.parameters['SERVO_2_MAX']
# vehicle.parameters['SERVO_2_MAX_1']
# vehicle.parameters['SERVO_2_MAX_2']
# vehicle.parameters['SERVO_2_MAX_3']
# vehicle.parameters['SERVO_2_MAX_MAX']
# vehicle.parameters['SERVO_2_MAX_MIN']
# vehicle.parameters['SERVO_3_MAX']
# vehicle.parameters['SERVO_3_MAX_1']
# vehicle.parameters['SERVO_3_MAX_2']
# vehicle.parameters['SERVO_3_MAX_3']
# vehicle.parameters['SERVO_3_MAX_MAX']
# vehicle.parameters['SERVO_3_MAX_MIN']
# vehicle.parameters['SERVO_4_MAX']
# vehicle.parameters['SERVO_4_MAX_1']
# vehicle.parameters['SERVO_4_MAX_2']
# vehicle.parameters['SERVO_4_MAX_3']
# vehicle.parameters['SERVO_4_MAX_MAX']
# vehicle.parameters['SERVO_4_MAX_MIN']
# vehicle.parameters['SERVO_5_MAX']
# vehicle.parameters['SERVO_5_MAX_1']
# vehicle.parameters['SERVO_5_MAX_2']
# vehicle.parameters['SERVO_5_MAX_3']
# vehicle.parameters['SERVO_5_MAX_MAX']
# vehicle.parameters['SERVO_5_MAX_MIN']
# vehicle.parameters['SERVO_6_MAX']
# vehicle.parameters['SERVO_6_MAX_1']
# vehicle.parameters['SERVO_6_MAX_2']
# vehicle.parameters['SERVO_6_MAX_3']
# vehicle.parameters['SERVO_6_MAX_MAX']
# vehicle.parameters['SERVO_6_MAX_MIN']
# vehicle.parameters['SERVO_7_MAX']
# vehicle.parameters['SERVO_7_MAX_1']
# vehicle.parameters['SERVO_7_MAX_2']
# vehicle.parameters['SERVO_7_MAX_3']
# vehicle.parameters['SERVO_7_MAX_MAX']
# vehicle.parameters['SERVO_7_MAX_MIN']
# vehicle.parameters['SERVO_8_MAX']
# vehicle.parameters['SERVO_8_MAX_1']
# vehicle.parameters['SERVO_8_MAX_2']
# vehicle.parameters['SERVO_8_MAX_3']
# vehicle.parameters['SERVO_8_MAX_MAX']
# vehicle.parameters['SERVO_8_MAX_MIN']
# vehicle.parameters['SERVO_9_MAX']
# vehicle.parameters['SERVO_9_MAX_1']
# vehicle.parameters['SERVO_9_MAX_2']
# vehicle.parameters['SERVO_9_MAX_3']
# vehicle.parameters['SERVO_9_MAX_MAX']
# vehicle.parameters['SERVO_9_MAX_MIN']
# vehicle.parameters['SERVO_10_MAX']
# vehicle.parameters['SERVO_10_MAX_1']
# vehicle.parameters['SERVO_10_MAX_2']
# vehicle.parameters['SERVO_10_MAX_3']
# vehicle.parameters['SERVO_10_MAX_MAX']
# vehicle.parameters['SERVO_10_MAX_MIN']
# vehicle.parameters['SERVO_11_MAX']
# vehicle.parameters['SERVO_11_MAX_1']
# vehicle.parameters['SERVO_11_MAX_2']
# vehicle.parameters['SERVO_11_MAX_3']
# vehicle.parameters['SERVO_11_MAX_MAX']
# vehicle.parameters['SERVO_11_MAX_MIN']
# vehicle.parameters['SERVO_12_MAX']
# vehicle.parameters['SERVO_12_MAX_1']
# vehicle.parameters['SERVO_12_MAX_2']
# vehicle.parameters['SERVO_12_MAX_3']
# vehicle.parameters['SERVO_12_MAX_MAX']
# vehicle.parameters['SERVO_12_MAX_MIN']
# vehicle.parameters['SERVO_13_MAX']
# vehicle.parameters['SERVO_13_MAX_1']
# vehicle.parameters['SERVO_13_MAX_2']
# vehicle.parameters['SERVO_13_MAX_3']
# vehicle.parameters['SERVO_13_MAX_MAX']
# vehicle.parameters['SERVO_13_MAX_MIN']
# vehicle.parameters['SERVO_14_MAX']
# vehicle.parameters['SERVO_14_MAX_1']
# vehicle.parameters['SERVO_14_MAX_2']
# vehicle.parameters['SERVO_14_MAX_3']
# vehicle.parameters['SERVO_14_MAX_MAX']
# vehicle.parameters['SERVO_14_MAX_MIN']
# vehicle.parameters['SERVO_15_MAX']
# vehicle.parameters['SERVO_15_MAX_1']
# vehicle.parameters['SERVO_15_MAX_2']
# vehicle.parameters['SERVO_15_MAX_3']
# vehicle.parameters['SERVO_15_MAX_MAX']
# vehicle.parameters['SERVO_15_MAX_MIN']
# vehicle.parameters['SERVO_16_MAX']
# vehicle.parameters['SERVO_16_MAX_1']
# vehicle.parameters['SERVO_16_MAX_2']
# vehicle.parameters['SERVO_16_MAX_3']
# vehicle.parameters['SERVO_16_MAX_MAX']
# vehicle.parameters['SERVO_16_MAX_MIN']
# vehicle.parameters['SERVO_1_TRIM']
# vehicle.parameters['SERVO_1_TRIM_1']
# vehicle.parameters['SERVO_1_TRIM_2']
# vehicle.parameters['SERVO_1_TRIM_3']
# vehicle.parameters['SERVO_1_TRIM_MAX']
# vehicle.parameters['SERVO_1_TRIM_MIN']
# vehicle.parameters['SERVO_2_TRIM']
# vehicle.parameters['SERVO_2_TRIM_1']
# vehicle.parameters['SERVO_2_TRIM_2']
# vehicle.parameters['SERVO_2_TRIM_3']
# vehicle.parameters['SERVO_2_TRIM_MAX']
# vehicle.parameters['SERVO_2_TRIM_MIN']
# vehicle.parameters['SERVO_3_TRIM']
# vehicle.parameters['SERVO_3_TRIM_1']
# vehicle.parameters['SERVO_3_TRIM_2']
# vehicle.parameters['SERVO_3_TRIM_3']
# vehicle.parameters['SERVO_3_TRIM_MAX']
# vehicle.parameters['SERVO_3_TRIM_MIN']
# vehicle.parameters['SERVO_4_TRIM']
# vehicle.parameters['SERVO_4_TRIM_1']
# vehicle.parameters['SERVO_4_TRIM_2']
# vehicle.parameters['SERVO_4_TRIM_3']
# vehicle.parameters['SERVO_4_TRIM_MAX']
# vehicle.parameters['SERVO_4_TRIM_MIN']
# vehicle.parameters['SERVO_5_TRIM']
# vehicle.parameters['SERVO_5_TRIM_1']
# vehicle.parameters['SERVO_5_TRIM_2']
# vehicle.parameters['SERVO_5_TRIM_3']
# vehicle.parameters['SERVO_5_TRIM_MAX']
# vehicle.parameters['SERVO_5_TRIM_MIN']
# vehicle.parameters['SERVO_6_TRIM']
# vehicle.parameters['SERVO_6_TRIM_1']
# vehicle.parameters['SERVO_6_TRIM_2']
# vehicle.parameters['SERVO_6_TRIM_3']
# vehicle.parameters['SERVO_6_TRIM_MAX']
# vehicle.parameters['SERVO_6_TRIM_MIN']
# vehicle.parameters['SERVO_7_TRIM']
# vehicle.parameters['SERVO_7_TRIM_1']
# vehicle.parameters['SERVO_7_TRIM_2']
# vehicle.parameters['SERVO_7_TRIM_3']
# vehicle.parameters['SERVO_7_TRIM_MAX']
# vehicle.parameters['SERVO_7_TRIM_MIN']
# vehicle.parameters['SERVO_8_TRIM']
# vehicle.parameters['SERVO_8_TRIM_1']
# vehicle.parameters['SERVO_8_TRIM_2']
# vehicle.parameters['SERVO_8_TRIM_3']
# vehicle.parameters['SERVO_8_TRIM_MAX']
# vehicle.parameters['SERVO_8_TRIM_MIN']
# vehicle.parameters['SERVO_9_TRIM']
# vehicle.parameters['SERVO_9_TRIM_1']
# vehicle.parameters['SERVO_9_TRIM_2']
# vehicle.parameters['SERVO_9_TRIM_3']
# vehicle.parameters['SERVO_9_TRIM_MAX']
# vehicle.parameters['SERVO_9_TRIM_MIN']
# vehicle.parameters['SERVO_10_TRIM']
# vehicle.parameters['SERVO_10_TRIM_1']
# vehicle.parameters['SERVO_10_TRIM_2']
# vehicle.parameters['SERVO_10_TRIM_3']
# vehicle.parameters['SERVO_10_TRIM_MAX']
# vehicle.parameters['SERVO_10_TRIM_MIN']
# vehicle.parameters['SERVO_11_TRIM']
# vehicle.parameters['SERVO_11_TRIM_1']
# vehicle.parameters['SERVO_11_TRIM_2']
# vehicle.parameters['SERVO_11_TRIM_3']
# vehicle.parameters['SERVO_11_TRIM_MAX']
# vehicle.parameters['SERVO_11_TRIM_MIN']
# vehicle.parameters['SERVO_12_TRIM']
# vehicle.parameters['SERVO_12_TRIM_1']
# vehicle.parameters['SERVO_12_TRIM_2']
# vehicle.parameters['SERVO_12_TRIM_3']
# vehicle.parameters['SERVO_12_TRIM_MAX']
# vehicle.parameters['SERVO_12_TRIM_MIN']
